###
# Sets up and configures Supervisor for Celery and Celerybeat
##
- name: create Supervisor template for Celery to run
  become: true
  template: 
    src: supervisor_celery.conf.j2
    dest: "/etc/supervisor/conf.d/{{ app_name }}_celery.conf"

- name: create Supervisor template for Celerybeat to run
  become: true
  template: 
    src: supervisor_celerybeat.conf.j2
    dest: "/etc/supervisor/conf.d/{{ app_name }}_celerybeat.conf"


- name: stop supervisor for celery
  become: true
  command: service supervisor stop

- name: pause for restart to take effect
  pause: seconds=2

- name: start supervisor for celery
  become: true
  command: service supervisor start
