###
# configures the server and installs the web application
##

- include: ubuntu.yml
  when: initial_setup 

- include: nginx_ssl.yml
  when: deploy_ssl

- include: nginx_no_ssl.yml
  when: not deploy_ssl

- include: git.yml

- include: mongo.yml
  when: initial_setup

- include: venv.yml
  when: initial_setup

- include: dependencies.yml
  when: initial_setup

- include: data.yml

- include: node.yml
  when: initial_setup
  
- include: npm.yml

- include: asgi.yml



