##
# Configuration for Nginx web server
##
- name: ensure Nginx is installed via the system package
  become: true
  apt: 
    name: nginx 
    state: present 
    update_cache: yes

- name: create nginx ssl directory if it does not exist
  become: true
  file: 
    path: "/etc/nginx/{{ app_name }}"
    state: directory

- name: write SSL certificate file
  become: true
  copy: 
    src: "{{ ssl_certs_dir }}/{{ app_name }}.crt"
    dest: "/etc/nginx/{{app_name}}.crt"

- name: write SSL key file
  become: true
  copy: 
    src: "{{ ssl_certs_dir }}/{{ app_name }}.key"
    dest: "/etc/nginx/{{ app_name }}.key"

- name: ensure default symbolic linked website is deleted
  become: true
  file: 
    path: /etc/nginx/sites-enabled/default 
    state: absent


- name: write SSL nginx configuration
  become: true
  template: 
    src: nginx_ssl.conf.j2
    dest: "/etc/nginx/conf.d/{{ app_name }}.conf"

- name: restart nginx
  become: true
  service: 
    name: nginx 
    state: restarted
